services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333

  postgres:
    build: ./.docker/postgres
    image: postgres:13
    container_name: postgresql_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste

volumes:
  external-storage:
    external: true